print("Hello. What is your name?")
name = input()
print("It's nice to meet you,",name + ". How old are you?")
age = input()
print("I see that you are still quite young at only", age + ".")
print("Where do you live?")
home = input()
print("Wow! I've always wanted to go to", home + ". Thanks for chatting with me.\nBye!")